package kurs.backend.domain.model;

public enum RequestType {

  // Auth
  LOGIN,
  LOGOUT,
  REGISTER,

  // Users (ADMIN)
  GET_USERS,
  GET_USER,
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,
  DEACTIVATE_USER,

  // Employees (ADMIN, MANAGER)
  GET_EMPLOYEES,
  GET_EMPLOYEES_BY_STORE,
  GET_EMPLOYEE,
  CREATE_EMPLOYEE,
  UPDATE_EMPLOYEE,
  DELETE_EMPLOYEE,
  FIRE_EMPLOYEE,

  // Stores (ADMIN, MANAGER read)
  GET_STORES,
  GET_STORES_ACTIVE,
  GET_STORE,
  GET_STORES_BY_WAREHOUSE,
  CREATE_STORE,
  UPDATE_STORE,
  DELETE_STORE,
  DEACTIVATE_STORE,

  // Warehouses (ADMIN, others read)
  // TODO implement stock transfer
  GET_WAREHOUSES,
  GET_WAREHOUSES_ACTIVE,
  GET_WAREHOUSE,
  CREATE_WAREHOUSE,
  UPDATE_WAREHOUSE,
  DELETE_WAREHOUSE,
  DEACTIVATE_WAREHOUSE,

  // Stock (all read, ADMIN/MANAGER/ACCOUNTANT write)
  GET_STOCK,
  GET_STOCK_BY_LOCATION,
  GET_STOCK_BY_PRODUCT,
  SET_STOCK,
  DELETE_STOCK,

  // Sales (CASHIER/ADMIN write, others read)
  GET_SALES_BY_STORE,
  GET_SALE,
  PROCESS_SALE,
  PROCESS_RETURN,

  // Timesheets (MANAGER/ACCOUNTANT/ADMIN read)
  GET_TIMESHEETS_BY_EMPLOYEE,
  GET_TIMESHEETS_BY_EMPLOYEE_PERIOD,
  GET_TIMESHEETS_BY_STORE,
  GET_ALL_TIMESHEETS,
  GET_ALL_TIMESHEETS_BY_PERIOD,

  // Reports (ACCOUNTANT, ADMIN)
  REPORT_SALES,
  REPORT_EMPLOYEE_EFFICIENCY,
  REPORT_EMPLOYEE_EFFICIENCY_BY_ID,
  REPORT_STORE_EFFICIENCY
}
